### ISSUE TITLE
Bug in section 5

### ISSUE THREAD

**Issue by nils-ohlmeier** [cdh4u/draft-dtls-sdp#19]
"Because of this, if unordered
   transport is used for DTLS association, new transport (3-tuple) MUST
   be allocated by at least on the end points so that DTLS packets can
   be de-multiplexed."

Should probably be: "Because of this, if unordered
   transport is used for DTLS association, new transport (3-tuple) MUST
   be allocated by at least **one of** the end points so that DTLS packets can
   be de-multiplexed."

**Comment by cdh4u** [comment]
Correct.

**Comment by cdh4u** [comment]
Fixed in version -16.
